### ISSUE TITLE
Creating project - Cannot find proj.db

### ISSUE THREAD

**Issue by vcuervo** [BGR-EGHA/LSAT#29]
Hi BGR,

I managed to install LSAT, but I'm having the following error when creating a new project: 
(lsat) C:\Users\vcuer\Documents\LSAT-main>python C:\Users\vcuer\Documents\LSAT-main\LSAT-main\startMenu_main.py
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
(lsat) C:\Users\vcuer\Documents\LSAT-main>

Any thoughts about what the error might be?
- My dem is in EPSG 32610 in tiff format. I tried with the testing dataset and got the same issue.
- My GDAL file is in the same directory C:\Users\vcuer\Documents\LSAT-main\LSAT-main\GDAL-3.4.3-cp310-cp310-win_amd64.whl
I attached the yml for reference.
Thanks!
[lsat.zip](https://github.com/BGR-EGHA/LSAT/files/9244789/lsat.zip)

**Comment by BGR-EGHA** [comment]
Hi vcuervo,

sounds to me like you experience the same issue as #7.
My answer there (https://github.com/BGR-EGHA/LSAT/issues/7#issuecomment-1004627385) should fix your issue.

EPSG 32610 should not be the issue here, as GDAL supports it.
After installing the .whl file you can delete it. You don't need to keep it around.

Kind regards
Nick

**Comment by vcuervo** [comment]
Hi Nick - 

It seems that setting the PROJ_LIB variable worked as I'm not getting that error. However, I'm getting this new one: 
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Any thoughts?
![image](https://user-images.githubusercontent.com/69084680/182653208-e7889145-6487-4e84-ab3e-d23d6e9061b1.png)

**Comment by vcuervo** [comment]
Nick, 

I solved the above problem. Thanks!
