### ISSUE TITLE
Crash when importing raster.

### ISSUE THREAD

**Issue by Luis4ever22** [BGR-EGHA/LSAT#37]
I found LSAT crashing when importing a new raster, specifically around this area:

https://github.com/BGR-EGHA/LSAT/blob/main/core/widgets/ImportData/importData_importRaster.py#L109

issue: `rasterNoDataLocation` being called before assignment; this happens because of this if statement

```
  if raster.nodata:
      if np.isnan(raster.nodata):
          np.nan_to_num(rasterarray, copy=False, nan=-9999)
          rasterNoDataLocation = np.argwhere(rasterarray == -9999)
      else:
          rasterNoDataLocation = np.argwhere(rasterarray == raster.nodata)
  else:
      rasterNoData = ((),()) # tuple of two empty tuples to indicate absence of NoData
```

note the outer  else statement sets a variable named `rasterNoData` instead of `rasterNoDataLocation` which means that if `if raster.nodata` is `False` then `rasterNoDataLocation` is never defined. Also the value of `rasterNoData` cannot be a tuple since `rasterNoDataLocation` is dealing with numpy arrays, hence a tuple would also fail later on line 114 (`rasterNoDataLocation.shape`) since tuples don't have the a property called shape (only numpy arrays do). I'm proposing this PR to fix both issues (tested locally, and now I can import my raster successfully) 

Pull Request: https://github.com/BGR-EGHA/LSAT/pull/36
@BGR-EGHA

**Comment by BGR-EGHA** [comment]
Thanks for catching that and fixing it right away. Sounds good to me.
I merged it. Please let us know if you encounter any more bugs / would like to see a feature added.

Thanks again and Cheers,
Nick
