### ISSUE TITLE
New project error 

### ISSUE THREAD

**Issue by UmutERDAG** [BGR-EGHA/LSAT#38]
when i click create project 
ERROR 1: PROJ: proj_identify: C:\Program Files\GDAL\projlib\\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation.
![resim_2023-01-05_125547042](https://user-images.githubusercontent.com/122015678/210752251-d292cb3d-be14-4e41-b2ce-33d049b57488.png)

please tell me how can i fix it?

**Comment by BGR-EGHA** [comment]
Hi,

I also think it looks like you have another version of GDAL (besides the one in your venv) installed. It could be that the PROJ_LIB environment variable is set to that other installation.
Can you try removing that variable and check if it works then?

Cheers,
Nick

/e See https://github.com/BGR-EGHA/LSAT/issues/7#issuecomment-1004627385

**Comment by UmutERDAG** [comment]
Problem solved. Thanks!

**Comment by BGR-EGHA** [comment]
You're welcome.

Cheers,
Nick
