### ISSUE TITLE
Error: No module named 'osgeo'

### ISSUE THREAD

**Issue by 9imrah** [BGR-EGHA/LSAT#43]
Hello,
I was trying to explore the LSAT tool but encountered with an error at starting of start menue:
File "D:\LSAT-1.0.1\BGR-EGHA-LSAT-3fa695c\startMenu_main.py", line 3, in <module>
    from osgeo import gdal
ModuleNotFoundError: No module named 'osgeo'

**Comment by BGR-EGHA** [comment]
Hello Nimrah,

it looks like you are missing the osgeo package or you are using an old version of GDAL that used `import gdal`. Either way, you should install a recent version of GDAL. On Windows, the easiest way is to download a .whl file provided [here](https://github.com/cgohlke/geospatial-wheels/releases) (version 3.6.1 tested) and install it with `python -m pip install *path to .whl file*`. Most likely, you will need the AMD64 version of the package corresponding to your installed Python version (Python 3.11 -> cp311, Python 3.10 -> cp310, etc.).

Cheers
Nick
