### ISSUE TITLE
  error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by 9imrah** [BGR-EGHA/LSAT#44]
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Partial import of sklearn during the build process.
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      Traceback (most recent call last):

**Comment by BGR-EGHA** [comment]
Hi Nimrah,

when did the error appear?
I assume it occurred while attempting to install scikit-learn?
If yes, try installing [Microsoft Build Tools for C++](https://visualstudio.microsoft.com/visual-cpp-build-tools/).
If that does not resolve the issue, please provide more information.

Kind regards
Nick

**Comment by 9imrah** [comment]
Hi, Dear Nick, I hope you are well. I installed Microsoft Build Tools C++, Now there is new error while installing the requierment.txt "python -m pip install -r requirements.txt" 

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by BGR-EGHA** [comment]
Hello Nimrah,

please post the complete output.

Cheers
Nick

**Comment by 9imrah** [comment]
File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-p7a0k4mr\overlay\Lib\site-packages\setuptools\msvc.py", line 190, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.2.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**I run this as well: python.exe -m pip install --upgrade pip**

**Comment by BGR-EGHA** [comment]
Hi,

looks like the visual C++ Build Tools are not correctly installed.
Can you try working through [this](https://devblogs.microsoft.com/python/unable-to-find-vcvarsall-bat/)?
With which package does the error appear?
Maybe you can get a compiled wheel from [here](https://github.com/cgohlke/geospatial-wheels/releases)?
Please post the complete output starting with the command you entered.

Cheers
Nick
