### ISSUE TITLE
LSAT not work

### ISSUE THREAD

**Issue by paulest** [BGR-EGHA/LSAT#7]
Hi all.

I have tried to use this software, but it's not working on my PC. I have Windows 10, and specifically, I have problems with the extent (see screenshot). I installed this software with the installer and  Python commands, but it's not working.

Please consider this issue. I'm Ph.D. student, and I'm very interesting to use this software for my landslide susceptibility research.

Best regards.

![screenshot](https://user-images.githubusercontent.com/6208952/147772330-13282495-1053-409b-ba57-10ebbb43373f.png)

**Comment by BGR-EGHA** [comment]
Hi Paul,

it looks like you are using the test dataset, which should work.

The steps to create a project with the test data are:
1. Specify the project location (with dialog)
2. Specify the Project name
3. Load the AW3D30.tif raster from the test dataset (with dialog) (this correctly fills EPSG code, Extent and cell size information)
4. Click "Create project"

If you deviated from the steps above, please tell me what you did differently.
Did you change any of the Spatial Reference fields by hand?

If you followed the steps above and it still does not work:
Which version of python do you use?
What is the output of `python -m pip freeze` ran from inside your virtual environment for LSAT.

If you do not already, consider using the current git version of LSAT and not the installer, as the one currently available is not up to date.

Kind regards
Nick

**Comment by paulest** [comment]
Hi Nick, thanks for your response.

I have followed the steps you indicate using the dialogs and without entering anything by hand, however the Extent boxes appear in red (same as when I consulted previously).
I attach a screenshot of the message that appeared in PowerShell and also a screenshot of freeze command. My version of Python is 3.9.1

I installed the software both ways (with the installer and via Python) however I get the same Extent error.

Thanks for your help!

Best regards.
Paul 

![Python_freeze_screen](https://user-images.githubusercontent.com/6208952/147945963-922c1048-0df5-41ad-b9b5-e0190a593433.png)
![Powershell_screen](https://user-images.githubusercontent.com/6208952/147945967-b28bdecd-370e-4632-aa1e-5fdef53cb11b.png)

**Comment by BGR-EGHA** [comment]
Hi Paul,

From your last screenshot it looks like LSAT/GDAL searches in the wrong directory for proj.db. After installing the GDAL .whl you should have proj.db in your virtual environment:
`\venv\Lib\site-packages\osgeo\data\proj\proj.db`
When I rename/remove that file I can recreate your issue.

The wrong path in the PROJ_LIB Environment variable could be related to the fact that you start LSAT as Admin.
Others had similiar problems (https://stackoverflow.com/questions/56764046/gdal-ogr2ogr-cannot-find-proj-db-error) where changing the environment variable seemed to help.
I did not have PROJ_LIB set and LSAT/GDAL defaulted to the path above.

Hope that helps.

Best regards,
Nick

**Comment by paulest** [comment]
Hi Nick,

I have solved the problem. The configuration of the PROJ_LIB environment variable was wrong, but by changing it, I was able to run the software correctly.

Thank you very much for your help!

Best regards.
Paul
